app/auth/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from flask import Blueprint
from . import views
from app.main import errors

auth = Blueprint('auth', __name__)

auth.add_url_rule('/login/', 'login', views.login, methods=['GET', 'POST'])
auth.add_url_rule('/logout/', 'logout', views.logout)
auth.add_url_rule('/registration/', 'register', views.register, methods=['GET', 'POST'])
auth.add_url_rule('/registration/su', 'register_su',
                      views.register, defaults={'create_su': True}, methods=['GET', 'POST'])
auth.add_url_rule('/add-user/', 'add_user', views.add_user, methods=['GET', 'POST'])
auth.add_url_rule('/users/', view_func=views.Users.as_view('users'))
auth.add_url_rule('/users/edit/<username>', view_func=views.User.as_view('edit_user'))
auth.add_url_rule('/su-users/', view_func=views.SuUsers.as_view('su_users'))
auth.add_url_rule('/su-users/edit/<username>', view_func=views.SuUser.as_view('su_edit_user'))
auth.add_url_rule('/user/settings/', view_func=views.Profile.as_view('settings'))
auth.add_url_rule('/user/password/', view_func=views.Password.as_view('password'))
auth.errorhandler(403)(errors.handle_forbidden)

app/main/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from flask import Blueprint
from . import views, admin_views, errors

main = Blueprint('main', __name__)

main.add_url_rule('/', 'index', views.list_posts)
main.add_url_rule('/posts/', 'posts', views.list_posts)
main.add_url_rule('/posts/<slug>/', 'post_detail', views.post_detail, methods=['GET', 'POST'])
main.add_url_rule('/post/<slug>/', 'post_detail_fix', views.post_detail, defaults={'fix': True})
main.add_url_rule('/posts/<slug>/preview/', 'post_preview', views.post_detail, defaults={'is_preview': True})
main.add_url_rule('/posts/<slug>/<post_type>/preview/', 'post_general_preview', views.post_detail_general)
main.add_url_rule('/pages/<slug>/', 'page_detail', views.post_detail,
                  methods=['GET', 'POST'], defaults={'post_type': 'page'})
main.add_url_rule('/archive/', 'archive', views.archive)
main.add_url_rule('/tweet/', 'tweet', views.tweet)
main.add_url_rule('/ticktack', 'ticktack', views.ticktack)
main.add_url_rule('/users/<username>/', 'author_detail', views.author_detail)
main.add_url_rule('/atom/', 'recent_feed', views.recent_feed)
main.add_url_rule('/sitemap.xml/', 'sitemap', views.sitemap)
main.errorhandler(404)(errors.page_not_found)
main.errorhandler(401)(errors.handle_unauthorized)
main.add_url_rule('/<path:invalid_path>', 'handle_unmatchable', errors.handle_unmatchable)


blog_admin = Blueprint('blog_admin', __name__)

blog_admin.add_url_rule('/', view_func=admin_views.AdminIndex.as_view('index'))

blog_admin.add_url_rule('/posts/', view_func=admin_views.PostsList.as_view('posts'))
blog_admin.add_url_rule('/posts/draft/', view_func=admin_views.DraftList.as_view('drafts'))
blog_admin.add_url_rule('/new-post/', view_func=admin_views.Post.as_view('new_post'))
blog_admin.add_url_rule('/posts/<slug>/', view_func=admin_views.Post.as_view('edit_post'))

blog_admin.add_url_rule('/pages/', view_func=admin_views.PostsList.as_view('pages'),
                        defaults={'post_type': 'page'})
blog_admin.add_url_rule('/pages/draft/', view_func=admin_views.DraftList.as_view('page_drafts'),
                        defaults={'post_type': 'page'})
blog_admin.add_url_rule('/new-page/', view_func=admin_views.Post.as_view('new_page'), defaults={'post_type': 'page'})

blog_admin.add_url_rule('/posts/statistics/', view_func=admin_views.PostStatisticList.as_view('post_statistics'))
blog_admin.add_url_rule('/posts/statistics/<slug>/',
                        view_func=admin_views.PostStatisticDetail.as_view('post_statistics_detail'))

blog_admin.add_url_rule('/posts/comments/', view_func=admin_views.Comment.as_view('comments'))
blog_admin.add_url_rule('/posts/comments/approved/', view_func=admin_views.Comment.as_view('comments_approved'), defaults={'status':'approved'})
blog_admin.add_url_rule('/posts/comments/spam/', view_func=admin_views.Comment.as_view('comments_spam'), defaults={'status':'spam'})
blog_admin.add_url_rule('/posts/comments/<pk>/action/', view_func=admin_views.Comment.as_view('comment_action'))
blog_admin.add_url_rule('/posts/comments/import/', view_func=admin_views.ImportCommentView.as_view('import_comments'))


blog_admin.add_url_rule('/su/posts/', view_func=admin_views.SuPostsList.as_view('su_posts'))
blog_admin.add_url_rule('/su/posts/<slug>/', view_func=admin_views.SuPost.as_view('su_post_edit'))
blog_admin.errorhandler(404)(errors.admin_page_not_found)
blog_admin.errorhandler(401)(errors.handle_unauthorized)
blog_admin.errorhandler(403)(errors.handle_forbidden)

app/main/forms.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from flask_mongoengine.wtf import model_form
from flask_wtf import Form
from wtforms import (StringField, PasswordField, BooleanField, TextAreaField, HiddenField, ValidationError, FileField,
                     RadioField)
from wtforms.validators import DataRequired, URL, Length, Email, Optional

from . import models


class PostForm(Form):
    title = StringField('Title', validators=[DataRequired()])
    slug = StringField('Slug', validators=[DataRequired()])
    raw = TextAreaField('Content')
    abstract = TextAreaField('Abstract')
    category = StringField('Category')
    tags_str = StringField('Tags')
    post_id = HiddenField('post_id')
    post_type = HiddenField('post_type')
    from_draft = HiddenField('from_draft')

    def validate_slug(self, field):
        if self.from_draft.data and self.from_draft.data == 'true':
            posts = models.Draft.objects.filter(slug=field.data)
        else:
            posts = models.Post.objects.filter(slug=field.data)
        if posts.count() > 0:
            if not self.post_id.data or str(posts[0].id) != self.post_id.data:
                raise ValidationError('slug already in use')

SuPostForm = model_form(models.Post, exclude=['pub_time',
                                              'update_time', 'content_html', 'category', 'tags', 'post_type'])


class CommentForm(Form):
    email = StringField(u'邮箱(必填，不公开)', validators=[DataRequired(), Length(1, 128), Email()])
    author = StringField(u'名称(必填)', validators=[DataRequired(), Length(1, 128)])
    homepage = StringField(u'主页(选填)', validators=[URL(), Optional()])
    content = TextAreaField(u'留言(必填，支持<small><span class="label label-info">markdown</span></small>)',
                            validators=[DataRequired()])
    comment_id = HiddenField('comment_id')


class SessionCommentForm(Form):
    email = HiddenField('* Email')
    author = HiddenField('* Name')
    homepage = HiddenField('Homepage')
    content = TextAreaField('* Comment', validators=[DataRequired()])
    comment_id = HiddenField('comment_id')


class ImportCommentForm(Form):
    content = TextAreaField('Content')
    json_file = FileField('Json File')
    import_format = RadioField('Import Format', choices=[('text', 'text'), ('file', 'file')], default='text')

app/main/views.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from urlparse import urljoin
from flask import request, render_template, abort, g, url_for, flash, redirect, session
from flask import current_app, make_response
from flask_login import current_user

from werkzeug.contrib.atom import AtomFeed
from mongoengine.queryset.visitor import Q

from . import models, signals, forms
from app.auth.models import User
from app.auth.permissions import reader_permission
from app.hia.config import HiaBlogSettings

PER_PAGE = HiaBlogSettings['pagination'].get('per_page', 10)
ARCHIVE_PER_PAGE = HiaBlogSettings['pagination'].get('archive_per_page', 10)


def get_base_data():
    pages = models.Post.objects.filter(post_type='page', is_draft=False)
    blog_meta = HiaBlogSettings['blog_meta']
    data = {'blog_meta': blog_meta, 'pages': pages}
    return data


def list_posts():
    flash(u"欢迎访问，本站是博主学习 Flask 的实验性网站，想查看更多博文可以访问 http://knarfeh.com", category='notice')
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')
    # categories = posts.distinct('category')
    tags = posts.distinct('tags')

    try:
        cur_page = int(request.args.get('page', 1))
    except ValueError:
        cur_page = 1

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    keywords = request.args.get('keywords')

    if keywords:
        posts = posts.filter(Q(raw__contains=keywords) | Q(title__contains=keywords))

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    # group by aggregate
    category_cursor = models.Post._get_collection().aggregate([{
        '$group': {
            '_id': {
                'category': '$category'
            },
            'name': {
                '$first': '$category'
            },
            'count': {
                '$sum': 1
            },
        }
    }])
    posts = posts.paginate(page=cur_page, per_page=PER_PAGE)

    data = get_base_data()
    data['posts'] = posts
    data['cur_category'] = cur_category
    data['category_cursor'] = category_cursor
    data['cur_tag'] = cur_tag
    data['tags'] = tags
    data['keywords'] = keywords
    return render_template('main/index.html', **data)


def post_detail(slug, post_type='post', fix=False, is_preview=False):
    if is_preview:
        if not g.identity.can(reader_permission):
            abort(401)
        post = models.Draft.objects.get_or_404(slug=slug, post_type=post_type)
    else:
        post = models.Post.objects.get_or_404(slug=slug, post_type=post_type) if not fix else models.Post.objects.get_or_404(fix_slug=slug, post_type=post_type)

    if post.is_draft and current_user.is_anonymous:
        abort(404)

    data = get_base_data()
    data['post'] = post

    if request.form:
        form = forms.CommentForm(obj=request.form)
    else:
        obj = {'author': session.get('author'), 'email': session.get('email'), 'homepage': session.get('homepage'), }
        form = forms.CommentForm(**obj)

    if request.form.get('hia-comment') and form.validate_on_submit():
        hiablog_create_comment(form, post)
        if post_type == 'post':
            url = '{0}#comment'.format(url_for('main.post_detail', slug=slug))
        elif post_type == 'page':
            url = '{0}#comment'.format(url_for('main.page_detail', slug=slug))
        else:
            print(u"post_type:" + str(post_type))
            abort(404)
        msg = u'评论成功, 等待管理者审查通过.'
        flash(msg, 'success')
        return redirect(url)

    data['allow_donate'] = HiaBlogSettings['donation']['allow_donate']
    data['donation_msg'] = HiaBlogSettings['donation']['donation_msg']

    data['allow_comment'] = HiaBlogSettings['blog_comment']['allow_comment']
    if data['allow_comment']:
        comment_type = HiaBlogSettings['blog_comment']['comment_type']
        comment_shortname = HiaBlogSettings['blog_comment']['comment_opt'][comment_type]
        comment_func = get_comment_func(comment_type)
        data['comment_html'] = comment_func(slug, post.title, request.base_url, comment_shortname, form=form) if comment_func else ''

    data['allow_share_article'] = HiaBlogSettings['allow_share_article']

    if not is_preview:
        signals.post_visited.send(current_app._get_current_object(), post=post)

    return render_template('main/post.html', **data)


def post_preview(slug, post_type='post'):
    return post_detail(slug=slug, post_type=post_type, is_preview=True)


def post_detail_general(slug, post_type):
    is_preview = request.args.get('is_preview', 'false')
    is_preview = True if is_preview.lower() == 'true' else False
    return post_detail(slug=slug, post_type=post_type, is_preview=is_preview)


def author_detail(username):
    author = User.objects.get_or_404(username=username)

    posts = models.Post.objects.filter(post_type='post', is_draft=False, author=author).order_by('-pub_time')
    cur_page = request.args.get('page', 1)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['user'] = author
    data['posts'] = posts

    return render_template('main/author.html', **data)


def get_comment_func(comment_type):
    comment_func = {
        'hiablog': hiablog_comment,
        'duoshuo': duoshuo_comment,
    }

    return comment_func.get(comment_type)


def hiablog_comment(post_id, post_title, post_url, comment_shortname, form=None, *args, **kwargs):
    template_name = 'main/comments.html'
    comments = models.Comment.objects(post_slug=post_id, status='approved').order_by('pub_time')
    data = {
        'form': form,
        'comments': comments,
        'slug': post_id,
    }
    return render_template(template_name, **data)


def hiablog_create_comment(form, post):
    comment = models.Comment()
    comment.author = form.author.data.strip()
    comment.email = form.email.data.strip()
    comment.homepage = form.homepage.data.strip() or None
    comment.post_slug = post.slug
    comment.post_title = post.title
    comment.md_content = form.content.data.strip()
    comment.save()
    session['author'] = form.author.data.strip()
    session['email'] = form.email.data.strip()
    session['homepage'] = form.homepage.data.strip()


def duoshuo_comment(post_id, post_title, post_url, duoshuo_shortname, *args, **kwargs):
    u"""
    Create duoshuo script by params
    :param duoshuo_shortname:
    :param post_id:
    :param post_title:
    :param post_url:
    :return:
    """
    template_name = 'main/misc/duoshuo.html'
    data = {
        'duoshuo_shortname': duoshuo_shortname,
        'post_id': post_id,
        'post_title': post_title,
        'post_url': post_url,
    }

    return render_template(template_name, **data)


def archive():
    posts = models.Post.objects.filter(post_type='post', is_draft=False).order_by('-pub_time')

    cur_category = request.args.get('category')
    cur_tag = request.args.get('tag')
    cur_page = request.args.get('page', 1)

    if cur_category:
        posts = posts.filter(category=cur_category)

    if cur_tag:
        posts = posts.filter(tags=cur_tag)

    posts = posts.paginate(page=int(cur_page), per_page=ARCHIVE_PER_PAGE)

    data = get_base_data()
    data['posts'] = posts

    return render_template('main/archive.html', **data)


def tweet():
    return render_template('main/tweet.html')


def ticktack():
    return render_template('main/ticktack.html')


def make_external(url):
    return urljoin(request.url_root, url)


def recent_feed():
    feed = AtomFeed('Recent Articles', feed_url=request.url, url=request.url_root)

    posts = models.Post.objects.filter(post_type='post', is_draft=False)[:15]
    for post in posts:
        feed.add(post.title, unicode(post.content_html),
                 content_type='html',
                 author=post.author.username,
                 url=make_external(post.get_absolute_url()),
                 updated=post.update_time,
                 published=post.pub_time)
    return feed.get_response()


def sitemap():
    """Generate sitemap.xml. Makes a list of urls and date modified."""
    pages = []

    #########################
    # static pages
    #########################

    ######################
    # Post Pages
    ######################

    posts = models.Post.objects.filter(is_draft=False, post_type='post')
    for post in posts:
        pages.append((post.get_absolute_url(), post.update_time.date().isoformat()))

    ######################
    # Blog-Page Pages
    ######################

    blog_pages = models.Post.objects.filter(is_draft=False, post_type='page')
    for page in blog_pages:
        pages.append((page.get_absolute_url(), page.update_time.date().isoformat()))

    sitemap_xml = render_template('main/sitemap.xml', pages=pages)
    response = make_response(sitemap_xml)
    response.headers["Content-Type"] = "application/xml"

    return response

app/templates/main/archive.html
{% extends 'base.html' %}

{% block title %}{{ blog_meta.name }}{% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7xi5vu.com1.z0.glb.clouddn.com/hiabackground.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>{{ blog_meta.name }}</h1>
          <hr class="small">
          <span class="subheading">Archive</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block main %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      <div class="row">
        {% for post in posts.items %}
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
          <!-- <img src="..." alt="..."> -->
            <div class="caption">
              <h3><a href="{{ url_for('main.post_detail', slug=post.slug) }}">{{ post.title }}</a></h3><hr>
              <p><strong>Abstract: </strong>{{ post.abstract }}</p>
              <p><strong>Author: </strong>{{ post.author }}</p>
              <p><strong>Date: </strong>{{ post.pub_time.strftime('%Y/%m/%d') }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

      <div class="row">
        {% import '_pagination.html' as pagination %}
        {{ pagination.render_pagination(posts) }}
      </div>
    </div>
  </div>
</div>

<hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {

    location.href = "/";
    return false;
  });
</script>
{% endblock %}

app/templates/main/comments.html
<a name="comment"></a>
<h2>评论</h2>

{% import "_msg.html" as messages %}
{{ messages.render_msg() }}

<table>
  {% for comment in comments %}
  <tr>
    <td style="width: 8%">
      <img class="media-object" src="{{ comment.get_gavatar_url() }}" alt="user-avatar">
    </td>
    <td>
      <h4>{{ comment.author }}
      {% if comment.homepage %}
      <a href="{{ comment.homepage }}" rel="nofollow" target="_blank"><i class="fa fa-home" aria-hidden="true"></i></a>
      {% endif %}
      </h4>
      <div>
        {{ comment.html_content|safe }}
      </div>
    </td>
    <td style="width: 5%">
      <small>{{ comment.pub_time.strftime('%Y/%m/%d') }}</small>
    </td>
  </tr>
  {% endfor %}
</table>

<h2>我要发表看法</h2>
<hr>

{% import "_form.html" as forms %}
<form method="POST" action="#comment">
  {{ forms.render(form) }}
  <button type="submit" class="btn btn-primary" name="hia-comment" value="hia-comment">Submit</button>
</form>
<br>

app/templates/main/index.html
{% extends 'base.html' %}

{% block title %}{{ blog_meta.name }}{% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7xi5vu.com1.z0.glb.clouddn.com/hiabackground.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>{{ blog_meta.name }}</h1>
        </div>
      </div>
    </div>
  </div>
</header>

{% endblock %}

{% block main %}

<div class="container">
  {% for message in get_flashed_messages() %}
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %}
  {% block page_content %}{% endblock %}
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-2 col-md-8 col-md-offset-1">
      {% for post in posts.items %}
      <div class="post-preview">
        <a href="{{ url_for('main.post_detail', slug=post.slug) }}">
          <h2 class="post-title">
            {{ post.title }}
          </h2>
        </a>
        <p class="post-subtitle">
          {{ post.abstract }}
        </p>
        <p class="post-meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.pub_time.strftime('%Y-%m-%d') }}</p>
      </div>
        {% if not loop.last %}
        <hr>
        {% endif %}
        {% else %}
          <p class="post-subtitle">
            No articles found here
          </p>
        {% endfor %}
        <!-- Pager -->
        <ul class="pager">
          {% if posts.has_next %}
            <li class="next">
              <a href="?page={{ posts.next_num }}
                {%- if cur_category %}&category={{ cur_category }}{% endif %}
                {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Older Posts &rarr;</a>
            </li>
            {% endif %}
            {% if posts.has_prev %}
              <li class="next"><a href="?page={{ posts.prev_num }}
                {%- if cur_category %}&category={{ cur_category }}{% endif %}
                {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Previous Posts</a></li>
            {% endif %}
        </ul>
    </div>
    <div class="col-lg-3 col-md-2">
      <h3>Tags</h3><hr/>
      {% for tag in tags %}
        <a href="?tag={{ tag }}" class="post-tag">
          {% if tag == cur_tag %}
          <span class="label label-primary">
            {{ tag }}
            <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
          </span>

          {% else %}
            <span class="label label-default">
              {{ tag }}
            </span>
          {% endif %}
        </a>
      {% endfor %}

      <h3>Category</h3><hr/>
      <div class="list-group">
        {% for category in category_cursor %}
        {% if category and category.name %}
          {% if cur_category == category.name %}
            <a href="?category={{ category.name }}" class="list-group-item category-list active">{{ category.name }}
            <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
            <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
          {% else %}
            <a href="?category={{ category.name }}" class="list-group-item category-list ">{{ category.name }}
            <span class="badge">&nbsp;{{ category.count }}&nbsp;</span></a>
          {% endif %}
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>

<hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.rm-filter').on('click', function (event) {

    location.href = "/";
    return false;
  });
</script>
{% endblock %}

app/templates/main/post.html
{% extends 'base.html' %}
{% block title %} {{ post.title }} {% endblock %}

{% block custom_head %}
    <link href="{{ url_for('static', filename='css/share.min.css') }}" rel="stylesheet">
{% endblock %}


{% block header %}
<header class="intro-header" style="background-image: url('http://7xi5vu.com1.z0.glb.clouddn.com/hiabackground.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="post-heading">
          <h1>{{ post.title }}</h1>
          <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2> -->
          <span class="meta">Posted by <a href="{{ url_for('main.author_detail', username=post.author.username) }}">{{ post.author.username }}</a> on {{ post.pub_time.strftime('%Y/%m/%d %H:%M:%S') }}</span>
          {% if post.category%}
          <span class="meta">Category: <a href="{{ url_for('main.index') }}?category={{ post.category }}">{{ post.category }}</a></span>
          {% endif %}
          <span class="meta">Tags:
            {% for tag in post.tags %}
            <a href="{{ url_for('main.index') }}?tag={{ tag }}">{{ tag }}</a>
            {% endfor %}
          </span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}
{% block main %}
<div class="container">
  <article>
    <!-- <div class="container"> -->
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          {{post.content_html|safe}}
        </div>
      </div>
    {% if allow_share_article and post.post_type=='post' %}
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1" align="center">
          <div class="share-component" data-sites="weibo,wechat,douban,twitter,qq,google,facebook,linkedin"></div>
        </div>
      </div>
      <br>
    {% endif %}
    {% if allow_donate and post.post_type=='post' %}
      <div class="row">
        <div align="center">
          <a id="upvote_post" href="{{ url_for('blog_admin.edit_post', slug=post.slug) }}?is_draft=False">
            <span class="fa fa-arrow-up fa-stack-2x">{{ post.upvotes }}</span>
          </a>
        </div>
      </div>
      <br>
      <br>
      <div class="row">
        <!-- donate -->
        <div class ="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <div align="center">
            <a id="btn_donate" class="btn_donate center" href="#" title="Donate"><span class="fa fa-jpy fa-stack-2x"></span></a>
          </div>
          <br>
          <!-- weixin -->
          <div id="donate_guide" class="donate_bar center hidden" align="center">
            <p>{{ donation_msg }}</p>
            <img src="http://7xi5vu.com1.z0.glb.clouddn.com/weixin_donate.JPG?imageView/2/w/300" title="Donate">
          </div>
        </div>
        <!-- donate -->
      </div>
    {% endif %}
    <!-- </div> -->
  </article>
    <br>
    <hr>
    {% if allow_comment %}
      <article>
        <!-- <div class="container"> -->
          <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              {{ comment_html|safe }}
            </div>
          </div>
        <!-- </div> -->
      </article>
    {% endif %}
</div>
{% endblock %}
{% block js %}
<script src="{{ url_for('static', filename='js/share.min.js') }}"></script>
<script type="text/javascript">
$('table').addClass('table');
$('#btn_donate').on('click', function(event){
    if($('#donate_guide').hasClass('hidden'))
        $('#donate_guide').removeClass('hidden');
    else
        $('#donate_guide').addClass('hidden');
    return false
});

$('#upvote_post').on('click', function(event){
    var url = $(this).attr('href');
    url = url + '&ajax=true';
    $.ajax({
        url: url,
        type: 'PUT',
        success: function(result){
            location.reload();
        }
    });
    return false;
});

</script>
{% endblock %}

app/templates/main/ticktack.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Ticktack</title>
    <link rel="stylesheet" href="static/ticktack/css/main.min.css">
</head>
<body>
    <div class="wrap">
        <p>人生只有 900 个月</p>
        <p>一切早已在暗中标好了价格</p>
        <p>我已经走过了<span class="left"></span>%</p>
        <canvas class="myLife" width="300px" height="300px"></canvas>
    </div>
    <script src="static/ticktack/js/main.min.js"></script>
    <hr>
    <p class="copyright text-muted" style="text-align: center">Copyright &copy;  <a target="_blank" href="https://github.com/DIYgod/Ticktack">Ticktack</a>.</p>
</body>
</html>

app/templates/main/tweet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>tweet system</title>
</head>
<body>
Under developing
</body>
</html>