app/auth/urls.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

from flask import Blueprint
from . import views
from app.main import errors

auth = Blueprint('auth', __name__)

auth.add_url_rule('/login/', 'login', views.login, methods=['GET', 'POST'])
auth.add_url_rule('/logout/', 'logout', views.logout)
auth.add_url_rule('/registration/', 'register', views.register, methods=['GET', 'POST'])
auth.add_url_rule('/registration/su', 'register_su',
                      views.register, defaults={'create_su': True}, methods=['GET', 'POST'])
auth.add_url_rule('/add-user/', 'add_user', views.add_user, methods=['GET', 'POST'])
auth.add_url_rule('/users/', view_func=views.Users.as_view('users'))
auth.add_url_rule('/users/edit/<username>', view_func=views.User.as_view('edit_user'))
auth.add_url_rule('/su-users/', view_func=views.SuUsers.as_view('su_users'))
auth.add_url_rule('/su-users/edit/<username>', view_func=views.SuUser.as_view('su_edit_user'))
auth.add_url_rule('/user/settings/', view_func=views.Profile.as_view('settings'))
auth.add_url_rule('/user/password/', view_func=views.Password.as_view('password'))
auth.errorhandler(403)(errors.handle_forbidden)

app/accounts/views.py
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import datetime

from flask import render_template, redirect, request, flash, url_for, current_app, session, abort
from flask.views import MethodView
from flask_login import login_user, logout_user, login_required, current_user
from flask_principal import Identity, AnonymousIdentity, identity_changed

from . import models, forms
from permissions import admin_permission, su_permission
from app.hia.config import HiaBlogSettings


def login():
    form = forms.LoginForm()
    if form.validate_on_submit():
        try:
            user = models.User.objects.get(username=form.username.data)
        except models.User.DoesNotExist:
            user = None

        if user and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            user.last_login = datetime.datetime.now
            user.save()

            identity_changed.send(current_app._get_current_object(), identity=Identity(user.username))
            return redirect(request.args.get('next') or url_for('blog_admin.index'))

        flash('Invalid username or password', 'danger')

    return render_template('accounts/login.html', form=form)


@login_required
def logout():
    logout_user()
    # Remove session keys set by Flask-Principal
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)

    # Tell Flask-Principal the user is anonymous
    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())

    flash('You have been logged out', 'success')
    return redirect(url_for('accounts.login'))


def register(create_su=False):
    if not HiaBlogSettings['allow_registration']:
        msg = 'Register is forbidden, please contact administrator'
        abort(403, msg)

    if create_su and not HiaBlogSettings['allow_su_creation']:
        msg = 'Register superuser is forbidden, please contact administrator'
        abort(403, msg)

    form = forms.RegistrationForm()
    if form.validate_on_submit():
        user = models.User()
        user.username = form.username.data
        user.password = form.password.data
        user.email = form.email.data
        user.display_name = user.username
        if create_su and HiaBlogSettings['allow_su_creation']:
            user.is_superuser = True
        user.save()
        return redirect(url_for('main.index'))
    return render_template('accounts/registration.html', form=form)


@login_required
def add_user():
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        user = models.User()
        user.username = form.username.data
        user.password = form.password.data
        user.email = form.email.data
        user.display_name = user.username
        user.save()
        return redirect(url_for('accounts.users'))
    return render_template('accounts/registration.html', form=form)


def get_current_user():
    user = models.User.objects.get(username=current_user.username)
    return user


class Users(MethodView):
    decorators = [login_required, admin_permission.require(401)]
    template_name = 'accounts/users.html'

    def get(self):
        users = models.User.objects.all()
        return render_template(self.template_name, users=users)


class User(MethodView):
    decorators = [login_required, admin_permission.require(401)]
    template_name = 'accounts/user.html'

    def get_context(self, username, form=None):
        if not form:
            user = models.User.objects.get_or_404(username=username)
            form = forms.UserForm(obj=user)
        data = {'form': form}
        return data

    def get(self, username, form=None):
        data = self.get_context(username, form)
        return render_template(self.template_name, **data)

    def post(self, username):
        form = forms.UserForm(obj=request.form)
        if form.validate():
            user = models.User.objects.get_or_404(username=username)
            if user.email != form.email.data:
                user.is_email_confirmed = False
            user.email = form.email.data
            # user.is_active = form.is_active.data
            # user.is_superuser = form.is_superuser.data
            user.role = form.role.data
            user.save()
            flash('Succeed to update user details', 'success')
            return redirect(url_for('accounts.edit_user', username=username))

        return self.get(username, form)

    def delete(self, username):
        user = models.User.objects.get_or_404(username=username)
        user.delete()

        if request.args.get('ajax'):
            return 'success'

        msg = 'Succeed to delete user'

        flash(msg, 'success')
        return redirect(url_for('accounts.users'))


class SuUsers(MethodView):
    decorators = [login_required, su_permission.require(401)]
    template_name = 'accounts/su_users.html'

    def get(self):
        users = models.User.objects.all()
        return render_template(self.template_name, users=users)


class SuUser(MethodView):
    decorators = [login_required, admin_permission.require(401)]
    template_name = 'accounts/user.html'

    def get_context(self, username, form=None):
        if not form:
            user = models.User.objects.get_or_404(username=username)
            user.weibo = user.social_networks['weibo'].get('url')
            user.weixin = user.social_networks['weixin'].get('url')
            user.twitter = user.social_networks['twitter'].get('url')
            user.github = user.social_networks['github'].get('url')
            user.facebook = user.social_networks['facebook'].get('url')
            user.linkedin = user.social_networks['linkedin'].get('url')

            form = forms.SuUserForm(obj=user)
        data = {'form': form}
        return data

    def get(self, username, form=None):
        data = self.get_context(username, form)
        return render_template(self.template_name, **data)

    def post(self, username):
        form = forms.SuUserForm(obj=request.form)
        if form.validate():
            user = models.User.objects.get_or_404(username=username)

            user.email = form.email.data
            user.is_email_confirmed = form.is_email_confirmed.data

            user.display_name = form.display_name.data
            user.biography = form.biography.data
            user.homepage_url = form.homepage_url.data or None
            user.social_networks['weibo']['url'] = form.weibo.data or None
            user.social_networks['weixin']['url'] = form.weixin.data or None
            user.social_networks['twitter']['url'] = form.twitter.data or None
            user.social_networks['github']['url'] = form.github.data or None
            user.social_networks['facebook']['url'] = form.facebook.data or None
            user.social_networks['linkedin']['url'] = form.linkedin.data or None
            user.save()

            msg = 'Succeed to update user profile'
            flash(msg, 'success')

            return redirect(url_for('accounts.su_edit_user', username=user.username))

        return self.get(form)


class Profile(MethodView):
    decorators = [login_required]
    template_name = 'accounts/settings.html'

    def get(self, form=None):
        if not form:
            # user = get_current_user()
            user = current_user
            user.weibo = user.social_networks['weibo'].get('url')
            user.weixin = user.social_networks['weixin'].get('url')
            user.twitter = user.social_networks['twitter'].get('url')
            user.github = user.social_networks['github'].get('url')
            user.facebook = user.social_networks['facebook'].get('url')
            user.linkedin = user.social_networks['linkedin'].get('url')
            form = forms.ProfileForm(obj=user)
        data = {'form': form}
        return render_template(self.template_name, **data)

    def post(self):
        form = forms.ProfileForm(obj=request.form)
        if form.validate():
            # user = get_current_user()
            user = current_user
            if user.email != form.email.data:
                user.email = form.email.data
                user.is_email_confirmed = False

            user.display_name = form.display_name.data
            user.biography = form.biography.data
            user.homepage_url = form.homepage_url.data or None
            user.social_networks['weibo']['url'] = form.weibo.data or None
            user.social_networks['weixin']['url'] = form.weixin.data or None
            user.social_networks['twitter']['url'] = form.twitter.data or None
            user.social_networks['github']['url'] = form.github.data or None
            user.social_networks['facebook']['url'] = form.facebook.data or None
            user.social_networks['linkedin']['url'] = form.linkedin.data or None
            user.save()

            msg = 'Succeed to update user profile'
            flash(msg, 'success')

            return redirect(url_for('blog_admin.index'))

        return self.get(form)


class Password(MethodView):
    decorators = [login_required]
    template_name = 'accounts/password.html'

    def get(self, form=None):
        if not form:
            form = forms.PasswordForm()
        data = {'form': form}
        return render_template(self.template_name, **data)

    def post(self):
        form = forms.PasswordForm(obj=request.form)
        if form.validate():
            # if not current_user.verify_password(form.current_password.data):
            #     return 'current password error', 403
            current_user.password = form.new_password.data
            current_user.save()
            # return 'waiting to code'
            msg = 'Succeed to update password'
            flash(msg, 'success')

            return redirect(url_for('accounts.password'))

        return self.get(form)

app/templates/_form.html
{% macro render(form) -%}

{% for field in form %}
  {% if field.type in ['CSRFTokenField', 'HiddenField'] %}
    {{ field() }}
  {% elif field.type == "BooleanField" %}
  <div class="checkbox">
  <label>
    {{ field() }} {{ field.label }}
  </label>

  </div>
  {% else %}
    <div class="clearfix {% if field.errors %} has-error {% endif %} form-group">
      {{ field.label }}
        {% if field.type == "TextAreaField" %}
          {{ field(class_="form-control", rows=10) }}
        {% else %}
          {{ field(class_="form-control") }}
        {% endif %}

        {% if field.errors or field.help_text %}
          <span class="help-block">
          {% if field.errors %}
            {{ field.errors|join(' ') }}
          {% else %}
            {{ field.help_text }}
          {% endif %}
          </span>
        {% endif %}
    </div>
  {% endif %}
{% endfor %}

{% endmacro %}%

app/templates/_msg.html
{% macro render_msg() %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <div class="flash_msg">
    {% for category, message in messages %}
      {% if category == 'message' %}
        {% set category='info' %}
      {% endif %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert" style="margin-bottom: 0px">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

{% endmacro %}

app/templates/_pagination.html
{% macro render_pagination(pagination) %}
  <nav class="text-center">
    <ul class="pagination">
      {% if not pagination.has_prev %}
        <li class="disabled">
          <span aria-hidden="true">&laquo;</span>
        </li>
      {% else %}
        <li>
          <a href="?page={{ pagination.prev_num }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}

      {% for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="?page={{ page }}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="?page={{ page }}"><strong>{{ page }}</strong></a></li>
          {% endif %}
        {% else %}
          <li><a href="#">...</a></li>
        {% endif %}
      {%- endfor %}

      {% if not pagination.has_next %}
        <li class="disabled next">
          <span aria-hidden="true">&raquo;</span>
        </li>
      {% else %}
        <li class="next">
          <a href="?page={{ pagination.next_num }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endmacro %}

app/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}Hia Blog Admin{% endblock %}</title>

  <link rel="icon" type="image/x-ico" href="{{ url_for('static', filename='img/favicon.ico') }}">

  <!-- Bootstrap Core CSS -->
  <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/hiablog.css') }}" rel="stylesheet">

  <!-- Custom CSS -->

  {% block css %}{% endblock %}
  <!-- Custom Fonts -->
  <style> html{display : none ; } </style>
  <script>
  if( self == top ) {
      document.documentElement.style.display = 'block' ;
  } else {
      top.location = self.location ;
  }
  </script>


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  {% import "_msg.html" as messages %}
  {{ messages.render_msg() }}

  <!-- Navigation -->
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#hiablog_navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Dashboard</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="hiablog_navbar">
        <ul class="nav navbar-nav">
          <li class="_active"><a href="{{ url_for('blog_admin.index') }}">Home <span class="sr-only">(current)</span></a></li>

          {% if g.identity.allow_write %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Posts <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.posts') }}">All Posts</a></li>
                <li><a href="{{ url_for('blog_admin.new_post') }}">New Post</a></li>
                <li><a href="{{ url_for('blog_admin.page_drafts') }}">Drafts</a></li>

                <li class="divider"></li>
                <li><a href="#">Tags</a></li>

                <li class="divider"></li>
                <li><a href="#">Category</a></li>
              </ul>
            </li>
          {% endif %}


          {% if g.identity.allow_edit %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pages <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{{ url_for('blog_admin.pages') }}">All Pages</a></li>
              <li><a href="{{ url_for('blog_admin.new_page') }}">New Page</a></li>
              <li><a href="{{ url_for('blog_admin.page_drafts') }}">Drafts</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Comments <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{{ url_for('blog_admin.comments') }}">Pending</a></li>
              <li><a href="{{ url_for('blog_admin.comments_approved') }}">Approved</a></li>
              <li><a href="{{ url_for('blog_admin.comments_spam') }}">Spam</a></li>
              <li class="divider"></li>
              <li><a href="{{ url_for('blog_admin.import_comments') }}">Import</a></li>
            </ul>
          </li>
          {% endif %}

          {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('auth.users') }}">All Users</a></li>
                <li><a href="{{ url_for('auth.add_user') }}">New User</a></li>
              </ul>
            </li>
          {% endif %}

          {% if g.identity.allow_admin %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Super Admin <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url_for('blog_admin.su_posts') }}">Posts & Pages</a></li>
                <li><a href="{{ url_for('auth.su_users') }}">Users</a></li>
                <li class="divider"></li>
                <li><a href="{{ url_for('blog_admin.post_statistics') }}">Posts Statistics</a></li>
              </ul>
            </li>
          {% endif %}
          </ul>

          <div class="collapse navbar-collapse" id="hiablog_navbar">
          <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ current_user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                  <li><a href="{{ url_for('auth.settings') }}">Settings</a></li>
                  <li class="divider"></li>
                  <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                  <!-- <li class="divider"></li>
                  <li><a href="#">Category</a></li> -->
              </ul>
            </li>
          {% else %}
              <li><a href="{{ url_for('auth.login') }}">Login</a></li>
              <li><a href="{{ url_for('auth.register') }}">Register</a></li>
          {% endif %}
          </ul>
        </div>
        </div>
      </div><!-- /.container-fluid -->
    </nav>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <div class="container">
        <!-- Main Content -->

        {%block main %}{% endblock %}
    </div>
    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
              <li>
                <a href="https://creativecommons.org/licenses/" target="_blank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li>
                <a href="https://github.com/knarfeh/" target="_blank">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted text-center">Copyright &copy; knarfeh 2016</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/bootbox.js/4.4.0/bootbox.min.js"></script>

    <!-- Custom Theme JavaScript -->
    {% block js %}
    {% endblock %}

</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% if post %}
  <meta name="title" content="{{ post.title }} | {{ blog_meta.name }}">
  <meta name="description" content="{{ post.abstract }}">
  <meta name="author" content="{{ post.author.username }}">
  <meta name="keywords" content="{{ post.tags|join(',') }}">
  {% else %}
  <meta name="title" content="{{ blog_meta.name }}">
  <meta name="description" content="{{ blog_meta.description }}">
  <meta name="author" content="{{ blog_meta.owner }}">
  <meta name="keywords" content="{{ blog_meta.keywords }}">
  {% endif %}

  <meta name="google-site-verification" content="{{ blog_meta.google_site_verification }}">
  <meta name="baidu-site-verification" content="{{ blog_meta.baidu_site_verification }}">
  <meta name="sogou_site_verification" content="{{ blog_meta.sogou_site_verification }}">

  <title>{% block title %}Hia Blog{% endblock %}</title>

  <!-- Bootstrap Core CSS -->

  <link rel="icon" type="image/x-ico" href="{{ url_for('static', filename='img/favicon.ico') }}">

  <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- Custom CSS -->
  <link href="{{ url_for('static', filename='css/clean-blog.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/hiablog.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="http://cdn.staticfile.org/highlight.js/8.3/styles/default.min.css">
  <link href="{{ url_for('main.recent_feed') }}"
    rel="alternate"
    title="Recent Changes"
    type="application/atom+xml">

  {% block custom_head %}{% endblock %}

    <!-- Custom Fonts -->
    <style> html{display : none ; } </style>
    <script>
    if( self == top ) {
        document.documentElement.style.display = 'block' ;
    } else {
        top.location = self.location ;
    }
    </script>

    <!-- <link href="http://libs.useso.com/js/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#hiablog_navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Home</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="hiablog_navbar">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{{ url_for('main.recent_feed') }}" target="_blank">RSS</a>
          </li>
          <li>
            <a href="{{ url_for('main.archive') }}">Archive</a>
          </li>
          <li>
            <a href="http://knarfeh.com">knarfeh.com</a>
          </li>
          <li>
            <a href="{{ url_for('main.ticktack', birthday=19940613) }}">Ticktack</a>
          </li>
          <li>
            <a href="http://ee-book.org">ee-book.org</a>
          </li>
          <li>
            <a href="{{ url_for('main.tweet') }}">Tweet</a>
          </li>
          {% for page in pages %}
          <li>
            <a href="{{ url_for('main.page_detail', slug=page.slug) }}">{{ page.slug }}</a>
          </li>
          {% endfor %}
          <li>
            {% if current_user.is_authenticated %}
            <a href="{{ url_for('blog_admin.index') }}">{{ current_user.username }}</a>
            {% endif %}
          </li>

        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}
    <!-- Main Content -->
    {%block main %}{% endblock %}
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <ul class="list-inline text-center">
              <li>
                <a href="http://weibo.com/2753500945">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-weibo fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
                <li>
                  <a href="http://twitter.com/knarfeh">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
                <li>
                  <a href="https://github.com/knarfeh/" target="_blank">
                    <span class="fa-stack fa-lg">
                      <i class="fa fa-circle fa-stack-2x"></i>
                      <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                    </span>
                  </a>
                </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; knarfeh 2016. licensed under
            <a target="_blank" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>.</p>
          </div>
        </div>
      </div>
    </footer>
    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="//cdn.bootcss.com/highlight.js/8.7/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-75002639-3', 'auto');
    ga('send', 'pageview');
    </script>
    {% block js %}
    {% endblock %}
</body>
</html>